deploy :
  runs-on : self-hosted
    
  needs: build

    steps :
      - name : Download build artifact
        uses : actions/download-artifact@v4
        with :
            name: myflask-artifact
            path: dist/myflask.zip 

      - name : create Zip

      - name : Copy zip to Ec2 Server

      - name : Connect to ec2 via ssh & deploy

      - name : Unzip 
      - name : Install requirements
      - name : Run Gunicorn
