name: python-ci

on:
  push:
    branches: 
      - feat/*
      - new_my1
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.12'
           cache: 'pip'
           

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
      - name: Run tests (pytest)
         # working-directory: ./myflask
        env:
          PYTHONPATH: .
        run: |
          pip install pytest 
    
          pytest -q
    

      - name : create Artifact
        run : |
          mkdir -p dist/
          cp -r myflask/. dist/

          sudo apt-get install -y zip unzip
          cd dist && zip -r myflask.zip .

     
      - name: Upload artifact (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: myflask-artifact
          path: dist/myflask.zip

      - name : Download build artifact
        uses : actions/download-artifact@v4
        with :
          name: myflask-artifact
          path: dist/

      - name : Copy zip to Ec2 Server
        uses :  appleboy/scp-action@v0.1.7
        with :
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/myflask.zip"
          target: "/home/${{ secrets.EC2_USER }}/"


      - name : Connect to ec2 via ssh  deploy
        uses : appleboy/ssh-action@v1.0.3
        with :
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
          
            cd /home/ubuntu
            mkdir -p app
            unzip -o myflask.zip -d app
            cd app
            python -m venv .venv 
            source .venv/bin/activate
            pip install -r requirements.txt gunicorn
         


