name: python-ci

on:
  push:
    branches: [ dev ]
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'   

    
      - name: Install dependencies
        run: |
          sudo apt install python3 python3-pip -y
          pip install -r requirements.txt
     
      - name: Run tests (pytest)

        run: |
          pip install pytest 
          pytest -q

      - name : create Artifact
        run : |
          mkdir -p dist/flaskapp
          cp -r app.py dist/flaskapp/
          cp -r templates dist/flaskapp/
          cp requirements.txt dist/flaskapp/
          python -m venv .venv && source .venv/bin/activate
          pip install -r requirements.txt gunicorn
          cd dist && zip -r myflask.zip myflask

     
      - name: Upload artifact (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: myflask-artifact
          path: dist/myflask.zip


    